In [47]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
a=np.add(x,y)
print(a)
s=np.subtract(x,y)
print(s)
m=np.multiply(x,y)
print(m)
d=np.divide(x,y)
print(d)

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]


In [63]:
X = np.array([[1,2], [3,4]])
print("sqrt row1")
print(np.sqrt(X)[0,:])
print("sqrt row2")
print(np.sqrt(X)[1,:])
print("sqrt column1")
print(np.sqrt(X)[:,0])
print("sqrt column2")
print(np.sqrt(X)[:,1])
print("max row1")
print(X[0,:].max())
print("max row2")
print(X[1,:].max())
print("max column1")
print(X[:,0].max())
print("max column2")
print(X[:,1].max())
print("min row1")
print(X[0,:].min())
print("min row2")
print(X[1,:].min())
print("min column1")
print(X[:,0].min())
print("min column2")
print(X[:,1].min())
print("median")
print(np.median(X))
print("std")
print(X.std())
print("mean")
print(X.mean())
print("exp")
print(np.exp(X))



sqrt row1
[1.         1.41421356]
sqrt row2
[1.73205081 2.        ]
sqrt column1
[1.         1.73205081]
sqrt column2
[1.41421356 2.        ]
max row1
2
max row2
4
max column1
3
max column2
4
min row1
1
min row2
3
min column1
1
min column2
2
median
2.5
std
1.118033988749895
mean
2.5
exp
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
